### ISSUE TITLE
Feature: Toast/Notify/Snackbar

### ISSUE THREAD

**Issue by Pratham82** [Pratham82/min-ui#31]
# Complete Toast/Notify/Snackbar

Feature: Toast/Notify/Snackbar

## Epic Description

This Feature will add a Toast component in component library

## List of Tasks (Complete in order)

- [x] Create a toast component for showing a toast on triggering of a certain task(button click)
- [ ] Show toast in various positions on the screen

**Comment by Manishsharma203** [comment]
looks good to go. You can add more variety of toasts as well in future.
